Repository rollkit/rollkit, pull requests merged in 2022-04, with the labels that each got.

#348 Avoid raw URL in readme.
  README.md
Labels: T:documentation, T:code-hygiene

#351 ci: add markdown linter
  .github/workflows/lint.yml
  .markdownlint.yaml
  CHANGELOG.md
  docs/lazy-adr/adr-001-node-interface.md
  docs/lazy-adr/adr-002-mempool.md
  docs/lazy-adr/adr-003-peer-discovery.md
  docs/lazy-adr/adr-004-core-types.md
  docs/lazy-adr/adr-005-serialization.md
  docs/lazy-adr/adr-006-da-interface.md
Labels: T:code-hygiene, C:ci

#353 fix: execute evmos build only once per PR
  .github/workflows/build-evmos.yml
Labels: C:ci

#361 Delete CHANGELOG.md
  CHANGELOG.md
Labels: C:optimint

#367 Deterministic protobuf builds with bufbuild
  README.md
  buf.gen.yaml
  buf.yaml
  proto/gen.sh
  proto/protoc.sh
  third_party/proto/gogoproto/gogo.proto
  types/pb/dalc/dalc.pb.go
  types/pb/optimint/optimint.pb.go
Labels: T:code-hygiene, C:ci

#366 fix: add missing configuration options
  config/config.go
Labels: T:bug

#370 Add Dockerfile to build da mock server
  .github/workflows/build-da-mockserv.yml
  docker/mockserv.Dockerfile
  go.sum
Labels: C:ci

#377 fix: keep track of DA height of latest applied block
  block/manager.go
  state/state.go
Labels: T:enhancement, C:block-sync

#382 deps: update libp2p
  go.mod
  go.sum
  p2p/client.go
  p2p/utils_test.go
Labels: C:p2p, T:dependencies
