Repository rollkit/rollkit, pull requests merged in 2022-10, with the labels that each got.

#547 fix: update proto files to v0.34.21
  proto/get_deps.sh
  proto/tendermint/abci/types.proto
Labels: T:dependencies

#554 replaced [8]byte with types.NamespaceID
  block/manager_test.go
  config/config.go
  config/config_test.go
  config/defaults.go
  da/celestia/celestia.go
  da/da.go
  da/grpc/grpc.go
  da/mock/mock.go
  da/test/da_test.go
  docs/lazy-adr/adr-004-core-types.md
  node/integration_test.go
  state/executor.go
  types/block.go
  types/serialization_test.go
Labels: T:code-hygiene

#556 Configure local-prefix for goimports linter
  .golangci.yml
  config/config.go
  config/config_test.go
  conv/config_test.go
  da/grpc/mockserv/cmd/main.go
  da/test/da_test.go
  rpc/json/handler.go
  store/store_test.go
Labels: T:code-hygiene, C:ci
