Repository rollkit/rollkit, pull requests merged in 2022-07, with the labels that each got.

#452 Add gossip fraud proof capability over p2p
  block/manager.go
  go.mod
  go.sum
  node/node.go
  p2p/client.go
  proto/optimint/optimint.proto
  types/block.go
  types/pb/optimint/optimint.pb.go
  types/serialization.go
  types/serialization_test.go
Labels: C:block-fraud-proofs

#404 Wrap errors returned from Store
  rpc/json/service_test.go
  store/store.go
Labels: T:enhancement

#474 fix: saving block height after committing validators to db
  block/manager.go
Labels: T:bug

#473 chore: move initGenesisChunks call into GetGenesisChunks
  node/node.go
  rpc/client/client.go
Labels: T:code-hygiene
