Repository rollkit/rollkit, pull requests merged in 2022-03, with the labels that each got.

#313 fix: make `TestValidatorSetHandling` stable
  CHANGELOG-PENDING.md
  rpc/client/client_test.go
Labels: T:testing

#314 fix: make `TestValidatorSetHandling` even more stable
  CHANGELOG-PENDING.md
  rpc/client/client_test.go
Labels: T:bug, T:testing

#315 Use google.golang.org/grpc v1.33.2 to be compatible with cosmos-sdk
  CHANGELOG-PENDING.md
  da/grpc/grpc.go
  go.mod
  go.sum
Labels: T:bug, T:sdk

#319 Add ProposerAddress as ValidatorInfo.Adress in Status rpc
  CHANGELOG-PENDING.md
  rpc/client/client.go
Labels: C:rpc

#332 Remove changelog checker.
  .github/workflows/pending-changelog-checker.yml
  CHANGELOG-PENDING.md
Labels: C:ci, no_changelog
