Repository rollkit/rollkit, pull requests merged in 2022-01, with the labels that each got.

#222 fix: gofmt block/manager.go and remove typo
  block/manager.go
Labels: no_changelog

#259 Use enum instead of strings for DB type
  node/node.go
Labels: T:code-hygiene, no_changelog

#260 Break out of loop instead of doing nothing
  node/node.go
Labels: T:bug, no_changelog

#262 Fix ineffective breaks
  state/indexer/block/kv/kv.go
  state/txindex/kv/kv.go
Labels: T:bug, no_changelog

#265 Fix missed breaks in selects
  state/indexer/block/kv/kv.go
  state/txindex/kv/kv.go
Labels: T:bug, no_changelog
