Repository rollkit/rollkit, pull requests merged in 2023-11, with the labels that each got.

#1304 ci: fix mempool test failures
  mempool/v1/mempool_test.go
  mempool/v1/mempool_test_helpers.go
Labels: T:testing, C:ci

#1310 ci: ignore third_party directory for tests and linters
  Makefile
Labels: T:testing, C:ci

#1279 specs: add validator set specs
  state/validators.md
Labels: T:spec-and-docs

#1295 Bring txsToByteSlices to parity with byteSlicesToTxs
  types/serialization.go
  types/serialization_test.go
Labels: T:code-hygiene

#1306 De-duplicate getRandomBlock across the repo
  da/test/da_test.go
  da/test/da_test_helpers.go
  node/full_client_test.go
  store/store_test.go
  store/test_helpers.go
  types/abci/block_test.go
  types/signed_header_test.go
  types/test_utils.go
  types/tx.go
  types/utils.go
  types/utils_test.go
Labels: T:code-hygiene

#1263 mempool spec
  mempool/mempool.md
Labels: T:spec-and-docs

#1297 fix: address slow shutdowns in aggregation loop
  block/manager.go
  node/full.go
  node/full_client_test.go
  state/txindex/indexer_service.go
  state/txindex/indexer_service_test.go
Labels: T:enhancement, C:ci

#1313 ci: add light client tests and refactor node test helpers
  node/full.go
  node/full_node_test.go
  node/light.go
  node/light_client_test.go
  node/node.go
  node/node_test.go
  types/utils.go
Labels: T:testing, C:light-client, C:ci

#1333 Add missing spec symlinks
  specs/src/SUMMARY.md
  specs/src/specs/block-executor.md
  specs/src/specs/full_node.md
  specs/src/specs/node.md
  specs/src/specs/rpc-equivalency-coverage.md
  specs/src/specs/validators.md
Labels: T:spec-and-docs

#1332 ci: handle shutdown in p2p client peer connect
  p2p/client.go
Labels: T:testing, C:ci

#1267 Test netInfo in full_client_test.go
  node/full_client_test.go
Labels: T:testing, C:rpc

#1242 New DA API
  config/defaults.go
  da/celestia/mock/server.go
  da/grpc/mockserv/mockserv.go
  da/newda/newda.go
  da/registry/registry.go
  da/registry/registry_test.go
  da/test/da_test.go
  go.mod
  go.sum
  node/full_client_test.go
  node/full_node_integration_test.go
  node/node_test.go
  rpc/json/helpers_test.go
Labels: T:enhancement, T:da-integration

#1337 Handle nil case in Header function
  node/full_client.go
Labels: T:code-hygiene

#1338 Change Hard Confirmed to DA Included
  block/block-manager.md
  block/block_cache.go
  block/block_cache_test.go
  block/manager.go
  block/manager_test.go
  node/full_node_integration_test.go
Labels: T:code-hygiene, T:spec-and-docs

#1336 block verify
  block/manager.go
  types/block.go
Labels: T:spec-and-docs, C:block-sync

#1335 add staking module differences to block_spec
  block/block-manager.md
  block/out-of-order-blocks.png
  block/termination.png
  types/block_spec.md
Labels: T:spec-and-docs

#1351 Stop indexer service in full node OnStop method
  node/full.go
  state/indexer-service.md
Labels: T:bug, P:high, C:ci, va

#1353 Bump config version
  RELEASE.md
  config/defaults.go
Labels: T:code-hygiene

#1354 Deduplicate client generation
  node/full.go
  node/full_client.go
  node/light.go
Labels: T:code-hygiene

#1301 Hardcode centralized sequencer behavior
  block/manager.go
  block/manager_test.go
  da/mock/mock.go
  go.mod
  go.sum
  node/crypto.go
  node/crypto_test.go
  node/full_client.go
  node/full_client_test.go
  node/full_node_integration_test.go
  node/helpers.go
  node/node_test.go
  proto/get_deps.sh
  proto/rollkit/rollkit.proto
  proto/rollkit/state.proto
  rpc/json/helpers_test.go
  state/executor.go
  state/executor_test.go
  store/store_test.go
  types/abci/block.go
  types/abci/block_test.go
  types/hashing.go
  types/header.go
  types/pb/rollkit/rollkit.pb.go
  types/pb/rollkit/state.pb.go
  types/serialization.go
  types/serialization_test.go
  types/signed_header.go
  types/signed_header_test.go
  types/state.go
  types/utils.go
  types/utils_test.go
Labels: T:code-hygiene, C: sequencing, va

#1361 Disable SyncLoop, RetrieveLoop, and BlockStoreRetrieveLoop in Aggregator
  node/full.go
Labels: T:code-hygiene

#1371 downgrade gogo protobuf and remove go-replace
  go.mod
  go.sum
  node/full_node.md
Labels: T:enhancement

#1328 chore: make sure all blocking chan calls are also watching for shutdown signals
  block/manager.go
  go.mod
  node/full.go
  node/full_client.go
  rpc/json/ws_test.go
Labels: T:code-hygiene

#1366 update val spec
  state/validators.md
Labels: T:spec-and-docs
