Repository rollkit/rollkit, pull requests merged in 2023-07, with the labels that each got.

#1026 Added signed header verification
  block/manager_test.go
  conv/abci/block.go
  da/test/da_test_helpers.go
  node/full_client.go
  node/full_client_test.go
  state/executor.go
  store/store_test.go
  store/test_helpers.go
  types/block.go
  types/header.go
  types/serialization_test.go
  types/signed_header.go
  types/signed_header_test.go
  types/test_utils.go
  types/validation.go
Labels: T:testing, C:header

#1057 README: fix typo
  README.md
Labels: T:documentation

#991 Adapting mempool for cometbft release
  go.mod
  go.sum
  mempool/v1/mempool.go
Labels: T:code-hygiene, C:feature-request

#1071 code-hygiene: Fix use of subtests in node integration tests
  node/full_node_integration_test.go
Labels: T:testing

#1074 set node id using p2p key instead of local host id
  node/block_exchange.go
  node/full_client.go
  node/full_client_test.go
  node/header_exchange.go
  p2p/client.go
Labels: T:bug

#1073 code-hygiene: Clean up node shutdown in testing
  block/manager.go
  block/manager_test.go
  da/test/da_test.go
  node/full_client_test.go
  node/full_node_integration_test.go
  node/full_node_test.go
  node/helpers_test.go
  state/txindex/kv/kv_test.go
  store/prefix_test.go
  store/store_test.go
Labels: T:testing, T:code-hygiene

#1078 remove: CheckBlockAvailability function from DA
  da/celestia/celestia.go
  da/da.go
  da/grpc/grpc.go
  da/grpc/mockserv/mockserv.go
  da/mock/mock.go
  da/test/da_test.go
  proto/dalc/dalc.proto
  types/pb/dalc/dalc.pb.go
Labels: T:code-hygiene

#1046 Fix data race issue for manager's lastState
  block/manager.go
  block/manager_test.go
Labels: T:bug, T:testing

#1083 Modify SubmitBlock to SubmitBlocks in DA interace
  block/manager.go
  da/celestia/celestia.go
  da/celestia/mock/server.go
  da/da.go
  da/grpc/grpc.go
  da/grpc/mockserv/mockserv.go
  da/mock/mock.go
  da/test/da_test.go
  proto/dalc/dalc.proto
  types/pb/dalc/dalc.pb.go
Labels: T:enhancement, C:types, C:data-availability, C:block-sync

#1090 fix CM_VERSION in proto/get_deps.sh
  proto/get_deps.sh
Labels: T:bug

#1093 golangci: add import duplication flag
  .golangci.yml
  node/block_exchange.go
  node/full_client.go
  node/header_exchange.go
  node/light_client.go
  node/test_helpers.go
  rpc/json/test_helpers.go
  types/test_utils.go
Labels: T:bug, C:ci

#1097 feat: bump celestia-openrpc
  go.mod
  go.sum
Labels: T:bug, T:dependencies

#1092 code-hygiene: Move fraud proofs to feature branch
  block/manager.go
  config/config.go
  config/config_test.go
  config/defaults.go
  go.mod
  go.sum
  mocks/Application.go
  node/full.go
  node/full_client_test.go
  node/full_node_integration_test.go
  node/helpers_test.go
  node/light.go
  node/proof_service_factory.go
  rpc/json/test_helpers.go
  state/executor.go
  state/executor_test.go
  types/state_fraud_proof.go
Labels: T:code-hygiene, C:state-fraud-proofs, C:abci

#1116 node: remove potential deadlock on chan capacity of zero
  node/full_client.go
Labels: T:code-hygiene

#1118 Move libs to libs/celestia-app
  libs/celestia-app/appconsts/appconsts.go
  libs/celestia-app/appconsts/consensus_consts.go
  libs/celestia-app/namespace/consts.go
  libs/celestia-app/namespace/namespace.go
  libs/celestia-app/namespace/namespace_test.go
  libs/celestia-app/namespace/random_blob.go
  libs/celestia-app/namespace/random_namespace.go
  libs/celestia-app/shares/compact_shares_test.go
  libs/celestia-app/shares/doc.go
  libs/celestia-app/shares/info_byte.go
  libs/celestia-app/shares/info_byte_test.go
  libs/celestia-app/shares/parse_compact_shares.go
  libs/celestia-app/shares/reserved_bytes.go
  libs/celestia-app/shares/reserved_bytes_test.go
  libs/celestia-app/shares/share_builder.go
  libs/celestia-app/shares/share_builder_test.go
  libs/celestia-app/shares/share_sequence.go
  libs/celestia-app/shares/share_sequence_test.go
  libs/celestia-app/shares/shares.go
  libs/celestia-app/shares/shares_test.go
  libs/celestia-app/shares/split_compact_shares.go
  libs/celestia-app/shares/split_compact_shares_test.go
  libs/celestia-app/shares/testdata/sample-block.json
  libs/celestia-app/shares/utils.go
  libs/celestia-app/shares/utils_test.go
  libs/celestia-app/testfactory/txs.go
Labels: T:code-hygiene
