Repository rollkit/rollkit, pull requests merged in 2023-06, with the labels that each got.

#968 change test.yml and makefile
  .github/workflows/test.yml
  Makefile
Labels: T:bug, C:ci, github_actions

#972 .github: add merge_group trigger for merge queue
  .github/workflows/ci_release.yml
  .github/workflows/test.yml
Labels: T:code-hygiene

#949 .github: update label from grooming to triage
  .github/workflows/housekeeping.yml
Labels: T:enhancement

#970 Fix go.mod
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: T:bug, T:dependencies, T:code-hygiene

#963 moved helpers to their own file
  da/test/da_test.go
  da/test/da_test_helpers.go
  libs/shares/info_byte_test.go
  libs/shares/shares_test.go
  mempool/v1/mempool_test.go
  mempool/v1/mempool_test_helpers.go
  node/full_client_test.go
  node/test_helpers.go
  rpc/json/service_test.go
  rpc/json/test_helpers.go
  state/indexer/block/kv/util.go
  store/store_test.go
  store/test_helpers.go
Labels: T:testing, T:code-hygiene

#953 fix: handling ErrNamespaceNotFound for node v0.10.0
  da/celestia/celestia.go
  da/celestia/celestia_test.go
  da/da.go
Labels: T:bug

#994 da: add celestia-openrpc dep
  da/celestia/celestia.go
  go.mod
  go.sum
Labels: C:data-availability

#1006 upgrade go-header to 0.2.8 which fixes the no peers found error
  go.mod
  go.sum
Labels: T:bug

#1010 Upgrade to go-cnc:v0.4.1, use cnc.Namespace
  block/manager_test.go
  config/config.go
  config/config_test.go
  config/defaults.go
  da/celestia/celestia.go
  da/celestia/mock/server.go
  da/da.go
  da/grpc/grpc.go
  da/grpc/mockserv/mockserv.go
  da/mock/mock.go
  da/test/da_test.go
  go.mod
  go.sum
  node/full_client_test.go
  node/full_node_integration_test.go
  state/executor.go
  state/executor_test.go
  types/block.go
Labels: backlog

#1011 README: add section with clearer compatibility and development steps
  Makefile
  README.md
Labels: T:documentation

#1012 adding a table to README showing rollkit compatibility
  README.md
Labels: backlog

#1014 Implement header interface for block and add block exchange service
  .gitignore
  block/manager.go
  go.mod
  go.sum
  node/block_exchange.go
  node/exchange.go
  node/full.go
  node/full_node_integration_test.go
  node/header_exchange.go
  node/helpers_test.go
  node/test_helpers.go
  types/block.go
Labels: C:p2p, C:block-sync

#1000 move proxyApp.VerifyFraudProofSync to ProofService
  block/manager.go
  node/full.go
  node/light.go
  node/proof_service_factory.go
Labels: T:enhancement, C:state-fraud-proofs
