Repository rollkit/rollkit, pull requests merged in 2023-10, with the labels that each got.

#1221 .github: add ready_for_review trigger for housekeeping workflow
  .github/workflows/housekeeping.yml
Labels: C:ci

#889 feat: Txs To Shares Roundtrip
  third_party/celestia-app/shares/compact_shares_test.go
  third_party/celestia-app/shares/parse_compact_shares.go
  third_party/celestia-app/shares/range.go
  third_party/celestia-app/shares/share_builder.go
  third_party/celestia-app/shares/shares.go
  third_party/celestia-app/shares/split_compact_shares.go
  third_party/celestia-app/shares/utils.go
  third_party/celestia-app/testfactory/txs.go
  types/tx.go
  types/tx_test.go
Labels: T:testing, c: serialization

#1224 Move block/header exchange to block package
  block/block_exchange.go
  block/exchange.go
  block/header_exchange.go
  node/full.go
  node/full_node_integration_test.go
  node/light.go
  node/test_helpers.go
Labels: T:code-hygiene

#1218 Remove unused fields in full node
  node/full.go
  node/full_node_integration_test.go
Labels: T:code-hygiene

#1227 Refactor full node constructor
  block/manager.go
  block/manager_test.go
  node/full.go
  node/full_client.go
  node/full_node_integration_test.go
Labels: T:code-hygiene

#1231 Decouple TestVerify into TestValidateBasic and TestVerify
  types/signed_header.go
  types/signed_header_test.go
  types/test_utils.go
Labels: T:testing, T:code-hygiene

#1228 Refactor full node test
  node/full_node_test.go
Labels: T:testing, T:code-hygiene

#1245 refactor: Rename exchange service to sync service for block and header
  block/block_sync.go
  block/header_sync.go
  block/syncer_status.go
  node/full.go
  node/full_node.md
  node/full_node_integration_test.go
  node/light.go
  node/test_helpers.go
Labels: T:code-hygiene

#1204 spec: Block Sync
  block/block-manager.md
  node/full_node.md
  specs/src/specs/header-sync.md
Labels: C:p2p, T:spec-and-docs, C:block-sync

#1247 chore: update readme for use in rollkit docs in place of "building-with-rollkit" page
  README.md
Labels: T:documentation

#1248 (chore): changes to the template for more guidance
  specs/template.md
Labels: T:documentation, T:code-hygiene

#1256 chore(deps): Bumps go-header and openrpc
  .gitignore
  block/block-manager.md
  block/block_sync.go
  block/header_sync.go
  go.mod
  go.sum
Labels: T:dependencies

#1251 Move header sync to block and create symlink in specs
  block/header-sync.md
  specs/src/specs/header-sync.md
Labels: T:code-hygiene

#1244 feat: add release trigger for merged PRs with create-release label
  .github/workflows/ci_release.yml
Labels: T:enhancement, github_actions

#1274 P2P specs
  p2p/p2p.md
Labels: T:documentation

#1265 Add store spec
  store/store.md
Labels: T:spec-and-docs

#1205 block validity spec
  specs/src/SUMMARY.md
  specs/src/specs/block-validity.md
  types/block_spec.md
Labels: T:spec-and-docs

#1287 loop through all txs before returning
  mempool/v1/mempool.go
  mempool/v1/mempool_test.go
Labels: backlog, va

#1288 deps: update grpc to v1.59.0 and remove replace directive
  da/grpc/grpc.go
  go.mod
  go.sum
Labels: T:dependencies

#1292 Make error message verbs/tense consistent
  node/crypto.go
  node/full.go
  node/light.go
Labels: T:code-hygiene
