Repository rollkit/rollkit, pull requests merged in 2023-03, with the labels that each got.

#771 Refactor: Header -> Signed Header
  block/manager.go
  conv/abci/block.go
  da/mock/mock.go
  da/test/da_test.go
  node/full_client.go
  node/full_client_test.go
  proto/rollkit/rollkit.proto
  state/executor.go
  state/executor_test.go
  store/store.go
  store/store_test.go
  types/block.go
  types/hashing.go
  types/pb/rollkit/rollkit.pb.go
  types/serialization.go
  types/serialization_test.go
  types/validation.go
Labels: C:header

#785 change Header gossip to SignedHeader gossip
  node/header_exchange.go
  types/block.go
  types/signed_header.go
Labels: C:header

#786 Remove sequencer gossip
  block/manager.go
  node/full.go
  node/full_node_integration_test.go
  node/header_exchange.go
  node/light.go
  types/signed_header.go
Labels: C:header

#799 deps: update libp2p
  go.mod
  go.sum
Labels: C:header

#803 Bug fix: lazy aggregator
  block/manager.go
  node/full_node_integration_test.go
Labels: C: sequencing

#800 deps: bump go-header
  go.mod
  go.sum
  node/header_exchange.go
  types/header.go
  types/signed_header.go
Labels: C:header

#806 types: signed header validator set - use tendermint types
  block/manager.go
  da/grpc/grpc.go
  da/grpc/mockserv/mockserv.go
  go.sum
  node/full_client_test.go
  proto/rollkit/rollkit.proto
  state/executor_test.go
  store/store_test.go
  types/block.go
  types/pb/rollkit/rollkit.pb.go
  types/serialization.go
  types/serialization_test.go
  types/validation.go
Labels: C:header

#810 enabling syncer for aggregator nodes
  node/header_exchange.go
Labels: C: sequencing

#814 manager: use validator set from state
  block/manager.go
  node/full_client_test.go
  node/full_node_integration_test.go
  rpc/json/service_test.go
  types/validation.go
Labels: C: sequencing

#822 Validate Aggregator hash from the validator set
  types/validation.go
Labels: C:header, C: sequencing
