Repository rollkit/rollkit, pull requests merged in 2023-12, with the labels that each got.

#1308 specs: add da spec
  da/da.go
  da/da.md
  proto/dalc/dalc.proto
  proto/protoc.sh
  types/pb/dalc/dalc.pb.go
Labels: T:spec-and-docs

#1381 Check block height before populating BlockCache
  block/manager.go
Labels: T:code-hygiene

#1390 Fix ci dead links
  .github/workflows/ci_release.yml
  block/manager.go
  da/da.go
  da/da.md
  go.mod
  go.sum
  mempool/mempool.md
  node/full.go
  node/full_client.go
  node/full_node.md
  proto/dalc/dalc.proto
  proto/protoc.sh
  rpc/json/ws_test.go
  specs/src/specs/state.md
  state/block-executor.md
  state/executor.go
  state/indexer_utils.go
  state/state.md
  state/validators.md
  types/pb/dalc/dalc.pb.go
Labels: T:bug, C:ci

#1388 Check block height before populating BlockCache
  block/manager.go
Labels: T:code-hygiene

#1376 only remove successfully submitted blocks from the pending blocks instead of reset
  block/manager.go
  block/pending_blocks.go
  block/pending_blocks_test.go
  mempool/mempool.md
  node/full_node_integration_test.go
Labels: T:bug

#1395 Fix markdown lint
  .github/mergify.yml
  state/block-executor.md
  state/validators.md
Labels: T:code-hygiene

#1396 fix: proactively check for shutdown event
  state/executor.go
Labels: T:code-hygiene

#1397 Remove based, keep vals - main
  block/manager.go
  block/manager_test.go
  node/full_node_integration_test.go
  state/executor_test.go
  store/store.go
  store/types.go
  types/signed_header.go
  types/utils.go
Labels: T:code-hygiene

#1378 Make try sync next block execute as many blocks as possible
  block/manager.go
  node/full_node_test.go
  node/helpers.go
  state/executor.go
  types/utils.go
Labels: T:code-hygiene

#1402 ci: fix panic in indexer
  mempool/clist_mempool.go
  node/full_client_test.go
  state/txindex/indexer_service.go
Labels: T:bug, C:ci

#1403 ci: update release flow to handle unique branch name and do patch releases on merge
  .github/workflows/ci_release.yml
Labels: T:bug, C:ci

#1406 fix: ensure node and services are watcing for the same shutdown signal from the context cancel
  block/manager.go
  node/full.go
  node/full_client.go
  node/full_node_integration_test.go
  node/light.go
  node/node_test.go
  state/txindex/indexer_service.go
  test/context/context.go
Labels: T:bug, C:ci

#1420 Add ConsensusParams updates handling logic (#1367)
  node/full_client.go
  state/executor.go
  state/executor_test.go
  state/indexer_utils.go
  types/params.go
  types/params_test.go
  types/serialization.go
  types/serialization_test.go
Labels: T:enhancement

#1386 Halt Sequencer if the app errors on a transaction
  block/manager.go
Labels: T:code-hygiene
