Repository rollkit/rollkit, pull requests merged in 2023-05, with the labels that each got.

#916 fix: Disable CI/CD linter check with rand library, fix server overlap, and data race issue
  da/test/da_test.go
  libs/testfactory/txs.go
  p2p/client.go
  p2p/gossip.go
Labels: T:bug, T:testing

#891 enable fraud service to full & light nodes and extend abci.FraudProof with go-fraud Proof interface
  README.md
  go.mod
  go.sum
  node/full.go
  node/header_exchange.go
  node/light.go
  node/proof_service_factory.go
  types/state_fraud_proof.go
Labels: C:state-fraud-proofs

#935 feat: Improvements to Makefile
  .yamllint.yml
  Makefile
Labels: T:enhancement, T:testing

#937 Fix race condition in TestValidatorSetHandling
  node/full_client_test.go
Labels: T:testing

#942 new readme
  README.md
Labels: T:documentation, T:dev-usability-and-ux

#928 fraud proof processing using go-fraud package
  block/manager.go
  node/full.go
  node/full_node_integration_test.go
  node/light.go
  node/proof_service_factory.go
  p2p/client.go
  state/executor.go
  types/header.go
Labels: C:state-fraud-proofs

#964 Remove header gossip from p2p module
  Makefile
  node/light.go
  p2p/client.go
Labels: C:p2p, T:code-hygiene, C:header

#962 fix header exchange init error
  node/header_exchange.go
Labels: T:bug
