Repository rollkit/rollkit, pull requests merged in 2023-01, with the labels that each got.

#610 feat: add ConnectionGater
  config/p2p.go
  node/node.go
  p2p/client.go
  p2p/client_test.go
  p2p/utils_test.go
Labels: T:enhancement

#696 Update required go vesion in readme
  README.md
Labels: T:documentation

#708 deps: update to go-header v0.1.0
  go.mod
  go.sum
  types/header.go
Labels: T:dependencies

#709 ci: request review from rollkit/celestia
  .github/dependabot.yml
Labels: C:ci
