Repository rollkit/rollkit, pull requests merged in 2023-09, with the labels that each got.

#1155 bump go verseion to 1.21 and use new builtin functions
  .github/workflows/ci_release.yml
  README.md
  go.mod
  go.sum
  node/full_client.go
Labels: T:dependencies

#1162 Recompute signature in signature header tests to make tests throw the right errors
  state/executor.go
  types/hashing.go
  types/signed_header_test.go
Labels: T:enhancement, T:testing, T:code-hygiene

#1165 Validate exact expected error in signed header verification tests
  types/header.go
  types/signed_header.go
  types/signed_header_test.go
Labels: T:enhancement, T:testing

#1139 Update mempool_test_helpers.go
  mempool/v1/mempool_test_helpers.go
Labels: T:testing

#1188 Switch DABlockTime to 15 seconds
  block/manager.go
  config/defaults.go
  da/test/da_test.go
Labels: T:code-hygiene, T:da-integration

#1178 feat: add go fmt to make fmt command
  Makefile
Labels: T:code-hygiene

#1161 adr-update: Update ADR 009
  docs/lazy-adr/adr-009-state-fraud-proofs.md
  docs/lazy-adr/figures/state_fraud_proofs.png
  docs/lazy-adr/sequence diagrams/State Fraud Proofs.txt
Labels: T:documentation, T:spec-and-doc

#1177 Use uint64 height types instead of int64
  block/manager.go
  block/manager_test.go
  conv/abci/block.go
  da/celestia/mock/server.go
  docs/lazy-adr/adr-009-state-fraud-proofs.md
  mempool/mempool.go
  mempool/v1/mempool.go
  mempool/v1/mempool_test.go
  mempool/v1/tx.go
  node/full_client.go
  node/full_client_test.go
  proto/rollkit/state.proto
  state/executor.go
  state/executor_test.go
  store/store_test.go
  types/block.go
  types/pb/rollkit/state.pb.go
  types/state.go
  types/test_utils.go
Labels: C:types, C:header

#1199 feat: init mdbooks for specs site with place holder files
  .github/workflows/specs-deploy.yml
  .gitignore
  block/block.md
  da/da.md
  mempool/mempool.md
  node/node.md
  p2p/p2p.md
  specs/.gitignore
  specs/README.md
  specs/book.toml
  specs/src/README.md
  specs/src/SUMMARY.md
  specs/src/specs/block.md
  specs/src/specs/da.md
  specs/src/specs/mempool.md
  specs/src/specs/node.md
  specs/src/specs/p2p.md
  specs/src/specs/state.md
  specs/src/specs/store.md
  specs/src/specs/template.md
  specs/template.md
  state/state.md
  store/store.md
Labels: T:documentation

#1190 updated README.md with releases
  README.md
  RELEASE.md
  assets/ci-release.png
  assets/manual-2.png
  assets/manual.png
Labels: T:documentation

#1200 Add Data Hash Validation to Block's `ValidateBasic`
  block/manager.go
  state/executor.go
  state/executor_test.go
  types/block.go
  types/hashing.go
Labels: T:enhancement, C:header, va

#1198 update dependency graph
  docs/specification/dependency-graph.drawio.svg
Labels: T:spec-and-doc

#1210 Update LICENSE
  LICENSE
Labels: T:code-hygiene

#1211 Revert "Update LICENSE"
  LICENSE
Labels: T:code-hygiene

#1206 use constants instead of literals
  node/full_client_test.go
  node/full_node_integration_test.go
  node/full_node_test.go
  rpc/json/test_helpers.go
  state/executor_test.go
Labels: T:code-hygiene

#844 header: verify NextValidatorsHash for light nodes
  block/manager.go
  conv/abci/block.go
  node/full_client_test.go
  proto/rollkit/rollkit.proto
  state/executor_test.go
  types/hashing.go
  types/header.go
  types/pb/rollkit/rollkit.pb.go
  types/serialization.go
  types/serialization_test.go
  types/test_utils.go
Labels: C: sequencing, va
