Repository rollkit/rollkit, pull requests merged in 2023-08, with the labels that each got.

#1123 upgrade cometbft to 0.37.2 and fix int64 to *big.Int issues
  go.mod
  go.sum
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/util.go
  state/indexer/query_range.go
  state/txindex/kv/kv.go
Labels: T:bug, T:dependencies

#1117 For loop audit
  da/mock/mock.go
  da/mock/util.go
  state/txindex/indexer_service.go
Labels: T:code-hygiene

#1085 Modify DA Test to use SubmitBlocks with multiple blocks
  da/celestia/mock/server.go
  da/test/da_test.go
  types/serialization.go
Labels: T:testing, T:da-integration, C:block-sync

#1140 deps: fix celestia-openrpc v0.1.2 breaking changes
  da/mock/mock.go
  da/mock/util.go
  go.mod
  go.sum
Labels: T:dependencies

#1144 test: use pkg httptest to avoid port conflict
  da/celestia/mock/server.go
  da/test/da_test.go
Labels: T:testing

#1145 test: update mock.Server to use httptest.Server
  da/celestia/mock/server.go
  da/test/da_test.go
Labels: T:testing

#1146 Enable subsecond block times using unix nano for Time in BaseHeader
  block/manager.go
  config/defaults.go
  da/mock/util.go
  state/executor.go
  state/indexer/query_range.go
  types/header.go
  types/signed_header_test.go
  types/test_utils.go
Labels: C:block-sync, C:fast-sync

#1151 remove cmsync usage
  mempool/clist/clist.go
  node/mempool.go
Labels: T:dependencies

#1152 Use channel instead of sync cond for RetrieveLoop and blockStoreRetri…
  block/manager.go
  block/pending_blocks.go
  node/full_client_test.go
Labels: T:code-hygiene
