Repository rollkit/rollkit, pull requests merged in 2024-04, with the labels that each got.

#1620 da: handle tx too large
  da/da.go
  da/da_test.go
Labels: T:da-integration

#1622 chore(ci): create repo specific PR template
  .github/pull_request_template.md
Labels: T:documentation, C:ci

#1621 feat(ci): add workflow for enforcing sementic pr titles
  .github/workflows/semantic-pull-request.yml
Labels: T:enhancement, C:ci

#1646 build: update x/net, libp2p and quic
  .github/workflows/ci_release.yml
  README.md
  go.mod
  go.sum
Labels: T:dependencies
