Repository rollkit/rollkit, pull requests merged in 2024-05, with the labels that each got.

#1641 feat: add vote extension support
  block/manager.go
  node/full_node_test.go
  state/executor.go
  state/executor_test.go
  store/store.go
  store/store_test.go
  store/types.go
  test/mocks/Store.go
  types/state.go
Labels: T:enhancement

#1681 fix(ci): fix failing golangci
  block/block-manager.md
  cmd/rollkit/commands/docs_gen.go
Labels: T:bug, C:ci

#1682 feat: add goreleaser for prebuilt binaries
  .github/workflows/ci_release.yml
  .github/workflows/goreleaser.yml
  .gitignore
  .goreleaser.yaml
  Makefile
Labels: C:ci
