Repository rollkit/rollkit, pull requests merged in 2024-01, with the labels that each got.

#1427 chore: remove unnecessary conversions
  .golangci.yml
  block/manager.go
  block/manager_test.go
  node/full_client_test.go
  rpc/json/handler.go
  store/store.go
  store/store_test.go
Labels: T:bug

#1411 TestTxGossipingAndAggregation fix
  node/full_node_integration_test.go
Labels: T:bug, C:ci

#1419 use go-ds-badger4
  go.mod
  go.sum
  store/kv.go
Labels: T:bug, va

#1418 Enforce centralized sequencer in p2p block gossiping
  block/manager.go
  block/manager_test.go
  node/full_client_test.go
  node/full_node_integration_test.go
  node/full_node_test.go
  node/node_test.go
  types/header.go
  types/signed_header.go
  types/signed_header_test.go
  types/utils.go
Labels: T:bug, T:code-hygiene

#1433 Move pending blocks out of attempts loop
  block/manager.go
Labels: T:bug, T:code-hygiene

#1434 Sevey/shutdown management
  node/full.go
  types/threadmanager.go
  types/threadmanager_test.go
Labels: T:enhancement, T:code-hygiene, C:ci

#1430 update README with latest release
  README.md
Labels: T:documentation

#1443 ci: fix release conditions
  .github/workflows/ci_release.yml
  .github/workflows/docker-build-da-mockserv.yml
Labels: T:bug, C:ci

#1442 chore: bump dep version for multiaddr
  go.mod
  go.sum
Labels: T:dependencies

#1425 fix WebSocket serialization
  rpc/json/handler.go
  rpc/json/service.go
  rpc/json/ws.go
  rpc/json/ws_test.go
Labels: c: serialization

#1460 Fix Inefficient usage of mutex in PendingBlocks
  block/pending_blocks.go
Labels: T:code-hygiene

#1459 Replace SyncStatus with atomic.Bool
  block/block_sync.go
  block/header_sync.go
  block/syncer_status.go
Labels: T:code-hygiene

#1466 Add a default erroring case on unknown enums in DA
  block/manager.go
Labels: T:code-hygiene

#1467 Do proposer check immediately
  block/manager.go
Labels: T:code-hygiene

#1468 Check for closure of txAvailable channel
  block/manager.go
Labels: T:code-hygiene

#1463 Compute empty evidence hash constantly
  types/abci/block.go
  types/abci/block_test.go
  types/hashing.go
Labels: T:code-hygiene

#1465 Fix Store related BB audit issues
  block/manager.go
  block/manager_test.go
  node/full.go
  node/full_client.go
  node/full_client_test.go
  node/full_node_integration_test.go
  node/full_node_test.go
  store/store.go
  store/store_test.go
  store/types.go
Labels: T:code-hygiene

#1469 refactor: replace switch statement with if condition for error handling
  block/manager.go
Labels: T:code-hygiene

#1480 Use sync.Map in block cache instead of one mutex lock
  block/block_cache.go
Labels: T:code-hygiene

#1498 chore: make log human readable
  state/executor.go
Labels: T:code-hygiene

#1478 Resolve multiple BB audit issues
  block/manager.go
  store/store.go
  types/block.go
  types/signed_header.go
  types/signed_header_test.go
Labels: T:bug, T:code-hygiene, bb-audit-issue

#1502 chore: bump cometbft to v0.38.4
  go.mod
  go.sum
Labels: T:dependencies, va

#1413 change genesis InitialHeight behavior
  block/manager.go
  block/manager_test.go
  types/state.go
Labels: T:bug, informal-audit-issue

#1505 Update auto_request_review.yml
  .github/auto_request_review.yml
Labels: C:ci

#1499 ignore validation failed error for the genesis block
  block/block_sync.go
  block/header_sync.go
Labels: T:bug

#1497 refactor: Use atomic.Uint64 for height in DefaultStore
  store/store.go
Labels: T:code-hygiene

#1516 Cast to uint64 from int64 instead of other way
  block/block_sync.go
  block/header_sync.go
  block/manager_test.go
  node/full_node_test.go
Labels: T:code-hygiene

#1508 mempool: Add metric size of pool in bytes
  mempool/clist_mempool.go
  mempool/metrics.go
Labels: T:enhancement
