Repository rollkit/rollkit, pull requests merged in 2024-03, with the labels that each got.

#1588 fix: retract v0.12.0 due to accidental publish
  go.mod
Labels: T:code-hygiene

#1589 Create an enum for "nodetype" instead of passing "light" and "full" as string literals to functions
  node/full_node_test.go
  node/light_client_test.go
  node/node_test.go
Labels: T:code-hygiene

#1568 Refactor pending blocks handling
  Makefile
  block/manager.go
  block/manager_test.go
  block/pending_blocks.go
  block/pending_blocks_test.go
  node/full_node_integration_test.go
  node/full_node_test.go
  store/store.go
  store/store_test.go
  store/types.go
  test/mocks/DA.go
Labels: T:enhancement

#1555 fix(manager): reduce the number of isProposer checks in manager
  block/manager.go
  block/manager_test.go
Labels: T:enhancement

#1580 Refactor GenerateKey to make it more robust
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/util.go
  state/txindex/kv/kv.go
  store/kv.go
  store/store.go
Labels: T:code-hygiene

#1599 add header and header by hash methods to jsonrpc
  rpc/json/service.go
  rpc/json/types.go
Labels: T:bug

#1601 fix(executor): limit block to da max blob size
  README.md
  block/manager.go
  node/node_test.go
  state/executor.go
  state/executor_test.go
Labels: T:da-integration

#1603 ci: add ci for the cli for rollkit start cmd
  .github/workflows/ci_release.yml
  cmd/rollkit/commands/run_node.go
  cmd/rollkit/docs/rollkit_start.md
Labels: T:testing, va

#1595 fix(manager): only reset custom gas price
  block/manager.go
  block/manager_test.go
  cmd/rollkit/docs/rollkit_start.md
  config/defaults.go
  node/full.go
Labels: T:da-integration

#1608 Update readme
  README.md
  RELEASE.md
  node/full_node.md
Labels: T:bug

#1609 feat: Add limit for pending DA submission blocks
  block/manager.go
  block/pending_blocks.go
  block/pending_blocks_test.go
  cmd/rollkit/docs/rollkit_start.md
  config/config.go
  node/full_node_integration_test.go
Labels: T:enhancement

#1613 test: add test for multiple rollups using the same namespace
  block/manager.go
  node/full_node_integration_test.go
  node/helpers_test.go
Labels: T:testing
