Repository rollkit/rollkit, pull requests merged in 2024-02, with the labels that each got.

#1507 da: add submit, get context timeouts
  da/da.go
  da/da_test.go
Labels: T:bug, C:data-availability

#1532 Disable ISRs in Block Data
  proto/rollkit/rollkit.proto
  state/executor.go
  types/block.go
  types/pb/rollkit/rollkit.pb.go
  types/serialization.go
  types/serialization_test.go
  types/tx_test.go
  types/utils.go
Labels: T:code-hygiene

#1536 Add test cases to consensus params validate
  types/params.go
  types/params_test.go
Labels: T:testing, T:code-hygiene

#1541 refactor: add missing stop ticker
  block/manager.go
Labels: T:code-hygiene

#1542 fix(da): update to go-da v0.4.0; add namespace flag
  config/config.go
  da/da.go
  da/da_test.go
  go.mod
  go.sum
  node/full.go
  node/full_client_test.go
  node/full_node_integration_test.go
  node/full_node_test.go
  node/helpers_test.go
  node/node_test.go
  rpc/json/helpers_test.go
Labels: T:dependencies

#1547 Status rpc
  node/full_client_test.go
Labels: T:bug

#1546 [DA] Fix error check for no blocks found in RetrieveBlocks()
  da/da.go
  da/da_test.go
Labels: T:bug

#1557 fix: make TestStatus stable
  node/full_client_test.go
Labels: T:testing

#1559 fix: mock CheckTx call for mempool recheck
  node/full_client_test.go
Labels: T:testing

#1563 fix: remove unnecessary node start in full client test
  node/full_client_test.go
Labels: T:enhancement

#1549 docs: fix typos
  state/block-executor.md
Labels: T:bug

#791 Add Rollkit CLI
  .github/workflows/lint.yml
  Makefile
  README.md
  cmd/README.md
  cmd/rollkit/commands/docs_gen.go
  cmd/rollkit/commands/root.go
  cmd/rollkit/commands/run_node.go
  cmd/rollkit/commands/version.go
  cmd/rollkit/docs/rollkit.md
  cmd/rollkit/docs/rollkit_completion.md
  cmd/rollkit/docs/rollkit_completion_bash.md
  cmd/rollkit/docs/rollkit_completion_fish.md
  cmd/rollkit/docs/rollkit_completion_powershell.md
  cmd/rollkit/docs/rollkit_completion_zsh.md
  cmd/rollkit/docs/rollkit_docs-gen.md
  cmd/rollkit/docs/rollkit_start.md
  cmd/rollkit/docs/rollkit_version.md
  cmd/rollkit/main.go
  config/config.go
  config/config_test.go
  go.mod
  go.sum
Labels: T:enhancement

#1554 Improve node and services closing
  block/block_sync.go
  block/header_sync.go
  block/manager.go
  node/full.go
  node/full_node_integration_test.go
  store/store.go
  store/store_test.go
  store/types.go
Labels: T:bug

#1577 Quick Fix: Fix wrong changes pushed to main branch from my PR #1544
  node/full_client_test.go
  node/helpers_test.go
Labels: T:enhancement, T:testing

#1574 test : Use IsType assertions in test
  node/full_node_test.go
  node/light_client_test.go
  node/node_test.go
Labels: T:enhancement, T:testing

#1535 fix(da): increase backoff for mempool errors
  block/manager.go
  block/manager_test.go
  cmd/rollkit/docs/rollkit_start.md
  config/config.go
  config/defaults.go
  da/da.go
  da/da_test.go
  da/mock/cmd/main.go
  da/mock/mock.go
  node/full.go
  node/full_client_test.go
  node/full_node_test.go
  node/helpers_test.go
Labels: T:bug, T:code-hygiene
