Repository rollkit/rollkit, pull requests merged in 2024-06, with the labels that each got.

#1691 chore: fix struct name in comment
  state/indexer/block/null/null.go
Labels: T:documentation

#1690 test: Add comprehensive tests for error scenarios in TestVoteExtension
  node/full_node_test.go
Labels: T:testing

#1737 fix(ci): update error checking for CLI ci to catch errors
  cmd/rollkit/commands/run_node.go
Labels: T:bug, C:ci

#1735 refactor: return types.State{} instead of state for err != nil case
  state/executor.go
Labels: T:code-hygiene

#1717 fix: Fix vote extension issues, add custom logic to handle secp256k1, fix rpc nilptr issues
  block/manager.go
  block/manager_test.go
  go.mod
  node/full_client.go
  node/full_client_test.go
  node/full_node_integration_test.go
  node/full_node_test.go
  node/node_test.go
  state/executor.go
  types/signed_header_test.go
  types/utils.go
  types/utils_test.go
Labels: T:bug
